[data-transition="none"]
== !

[quote, Edsger Dijkstra]
""
The use of COBOL cripples the mind;
its teaching should, therefore, be regarded as a criminal offense.
""

[data-transition="none"]
=== !

```
        LOAD    0
LOOP    STORE   TOTAL
        IN
        JINEG   DONE
        ADD     TOTAL
        JUMP    LOOP

DONE    PRINT   "The total is: "
        LOAD    TOTAL
        OUT
        LINE
        HALT

        %
        1
        2
        3
        -1
```

[NOTE.speaker]
--
We weren't taught COBOL but we were taught CESIL - Computer Education Symbolic Instruction Language.
CESIL was like a very simple assembly language, but also has the touch of COBOL.  Note the layout here, in the columns.  The % marks the start of the 'runtime section', where the runtime data lives.

At the time, the only computer we had that could run CESIL was an RM 380-Z, and classroom times was, I understand, quite strictly rostered.  My friend Scott decided to write a CESIL interpreter in
Spectrum BASIC as part of his course work, so I did all my CESIL course work using that.
--

[data-transition="none"]
=== !
[quote, Dijkstra again]
""
Goto Considered Harmful
""
[NOTE.speaker]
--
Letter published in CACM in March 1968.  How many people here are familiar with the
title but haven't read the letter.  Me!
--

[data-transition="none"]
=== !

[quote, Frank Rubin]
""
'GOTO Considered Harmful' Considered Harmful
""
[NOTE.speaker]
--
Frank Rubin published a criticism of Dijkstra's letter in the March 1987 CACM where
it appeared under the title "'GOTO Considered Harmful' Considered Harmful".
Not using Goto, coupled with single entry/single exit lead me to write some truely
ugly looking code.

In truth, Dijkstra's original title was "A case against the Goto statement" which is
rather milder.  The "considered harmful" title comes from Niklaus Wirth, who was CACM
editor at the time, and of course it plays directly to Wirth's ideas about programming.
--

[data-transition="none"]
=== !

[quote, Brian W. Kernighan]
""
Pascal was originally intended primarily as a teaching language,
but it has been more and more often recommended as a language for
serious programming as well, for example, for system programming
tasks and even operating systems.

Pascal, at least in its standard form, is just plain not suitable
for serious programming.
""

[NOTE.speaker]
--
From Why Pascal is Not My Favourite Programming Language

Article published by Kernighan in 1981, and is largely based on his experience
rewriting his 1976 book, Software Tools, co-authored with PJ Plauger, in Pascal.
(The original book was written using Ratfor - a preprocessor for Fortran, which among
other things replaced Goto with other control structures).

Why did Kernighan and Plauger choose Pascal.  Portability!
--
